#!/usr/bin/env bash
#This script installs nginx as webserver on ubuntu machine

# install nginx
apt update -y
apt install -y nginx

# allow firewall connection on HTTP Port 80
ufw allow 'Nginx HTTP'

# create index.html to be used at root
echo "Hello World!" > index.html

# move the index.html to root folder
mv index.html /var/www/html

# append redirection after server_name line
printf %s "server {
    listen 80;
    listen [::]:80 default_server;

    root /var/www/html;
    index  index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.github.com/Nwaigba66;
    }
    
}" > /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart
