#!/usr/bin/env bash
# This script displays numbers from 1 to 100, FizzBuzz when number is a multiple of 3 & 5,
# Fizz when number is a multiply of 3 only and Buzz when number is a multiple of 5 only.

for ((i=1; i<=100; i++))
do
	if ((i%15 == 0))
	then 
		echo "FizzBuzz"
	elif ((i%3 == 0))
	then
		echo "Fizz"
	elif ((i%5 == 0))
	then
		echo "Buzz"
	else
		echo $i
	
