#!/usr/bin/env bash
# This script displays content from file /etc/passwd with only fields username, user id and home directory path.

while read -r line
do
        username=$(echo "$line" | cut -d ':' -f1)
	user_id=$(echo "$line" | cut -d ':' -f3)
	home_dir=$(echo "$line" | cut -d ':' -f6)

        echo "$username:$user_id:$home_dir"
done < /etc/passwd
