#!/usr/bin/env bash
# This script loops from 1 to 20 and prints "bad luck from China" on 4th iteration, "bad luck from Japan" on 9th, "bad luck from Italy" for 17th iteration and numbers for the rest

i=1
while [ $i -lt 21 ]
do
	echo $i
	case $i in
	4)
		echo "bad luck from China" ;;
	9)
		echo "bad luck from Japan" ;;
	17)
		echo "bad luck from Italy" ;;
	esac
      
